// ─────────────────────────────────────────────────────────────────────────────
// 角色 Sprite 清單
// 新增角色：把 GIF 放進 public/sprites/，在下方加一筆即可
// ─────────────────────────────────────────────────────────────────────────────

export interface SpriteDefinition {
  id: string
  name: string
  description: string
  idleGif: string
  walkGif: string
  restGif: string
}

export const SPRITE_REGISTRY: SpriteDefinition[] = [
  // ── 狗狗系列 ────────────────────────────────────────────────────────────────
  {
    id: 'dog-chill',
    name: '慵懶狗',
    description: '能坐著就不站著',
    idleGif: '/sprites/Sprite-0004.gif',
    walkGif: '/sprites/Sprite-0001.gif',
    restGif: '/sprites/Sprite-0015.gif',
  },
  {
    id: 'dog-happy',
    name: '活潑狗',
    description: '永遠充滿活力！',
    idleGif: '/sprites/Sprite-0013.gif',
    walkGif: '/sprites/Sprite-0001.gif',
    restGif: '/sprites/Sprite-0015.gif',
  },
  {
    id: 'dog-cool',
    name: '酷狗',
    description: '低調但超強',
    idleGif: '/sprites/Sprite-0021.gif',
    walkGif: '/sprites/Sprite-0002.gif',
    restGif: '/sprites/Sprite-0016.gif',
  },
  {
    id: 'dog-hype',
    name: '衝衝狗',
    description: '截止日前最可靠的人',
    idleGif: '/sprites/Sprite-0005.gif',
    walkGif: '/sprites/Sprite-0003.gif',
    restGif: '/sprites/Sprite-0017.gif',
  },
  // ── 人類系列 ────────────────────────────────────────────────────────────────
  {
    id: 'dwarf',
    name: '矮人戰士',
    description: '矮小但衝勁十足的戰場老手',
    idleGif: '/sprites/dwarf-idle.gif',
    walkGif: '/sprites/dwarf-walk.gif',
    restGif: '/sprites/dwarf-rest.gif',
  },
  {
    id: 'gladiator',
    name: '鬥士',
    description: '戴鐵面具的神秘格鬥家',
    idleGif: '/sprites/gladiator-idle.gif',
    walkGif: '/sprites/gladiator-walk.gif',
    restGif: '/sprites/gladiator-rest.gif',
  },
  {
    id: 'cyclops',
    name: '獨眼巨人',
    description: '壯碩有力，辦公室最重量級成員',
    idleGif: '/sprites/cyclops-idle.gif',
    walkGif: '/sprites/cyclops-walk.gif',
    restGif: '/sprites/cyclops-rest.gif',
  },
  // ── 城鎮人物系列 ────────────────────────────────────────────────────────────
  {
    id: 'td-000',
    name: '大鬍子老大',
    description: '江湖歷練豐富，說話算話',
    idleGif: '/sprites/td-000-idle.gif',
    walkGif: '/sprites/td-000-walk.gif',
    restGif: '/sprites/td-000-rest.gif',
  },
  {
    id: 'td-001',
    name: '紅衣少女',
    description: '活潑外向，永遠是派對靈魂',
    idleGif: '/sprites/td-001-idle.gif',
    walkGif: '/sprites/td-001-walk.gif',
    restGif: '/sprites/td-001-rest.gif',
  },
  {
    id: 'td-002',
    name: '藍衣女孩',
    description: '冷靜分析，理性至上',
    idleGif: '/sprites/td-002-idle.gif',
    walkGif: '/sprites/td-002-walk.gif',
    restGif: '/sprites/td-002-rest.gif',
  },
  {
    id: 'td-003',
    name: '棕髮旅人',
    description: '走過許多地方，見多識廣',
    idleGif: '/sprites/td-003-idle.gif',
    walkGif: '/sprites/td-003-walk.gif',
    restGif: '/sprites/td-003-rest.gif',
  },
  {
    id: 'td-004',
    name: '黑髮青年',
    description: '沉默是金，行動力超強',
    idleGif: '/sprites/td-004-idle.gif',
    walkGif: '/sprites/td-004-walk.gif',
    restGif: '/sprites/td-004-rest.gif',
  },
  {
    id: 'td-005',
    name: '墨鏡型男',
    description: '永遠帶著太陽眼鏡，酷到不行',
    idleGif: '/sprites/td-005-idle.gif',
    walkGif: '/sprites/td-005-walk.gif',
    restGif: '/sprites/td-005-rest.gif',
  },
  {
    id: 'td-006',
    name: '制服警衛',
    description: '盡忠職守，辦公室秩序守護者',
    idleGif: '/sprites/td-006-idle.gif',
    walkGif: '/sprites/td-006-walk.gif',
    restGif: '/sprites/td-006-rest.gif',
  },
  {
    id: 'td-007',
    name: '警察局長',
    description: '鐵面無私，公正嚴明',
    idleGif: '/sprites/td-007-idle.gif',
    walkGif: '/sprites/td-007-walk.gif',
    restGif: '/sprites/td-007-rest.gif',
  },
  {
    id: 'td-008',
    name: '白髮劍客',
    description: '身經百戰，出手必有把握',
    idleGif: '/sprites/td-008-idle.gif',
    walkGif: '/sprites/td-008-walk.gif',
    restGif: '/sprites/td-008-rest.gif',
  },
  {
    id: 'td-009',
    name: '銀髮紳士',
    description: '品味獨到，舉止優雅',
    idleGif: '/sprites/td-009-idle.gif',
    walkGif: '/sprites/td-009-walk.gif',
    restGif: '/sprites/td-009-rest.gif',
  },
  {
    id: 'td-010',
    name: '休閒棕髮女',
    description: '輕鬆應對每件事，壓力不上身',
    idleGif: '/sprites/td-010-idle.gif',
    walkGif: '/sprites/td-010-walk.gif',
    restGif: '/sprites/td-010-rest.gif',
  },
  {
    id: 'td-011',
    name: '粉髮個性女',
    description: '勇於打破常規，創意無限',
    idleGif: '/sprites/td-011-idle.gif',
    walkGif: '/sprites/td-011-walk.gif',
    restGif: '/sprites/td-011-rest.gif',
  },
  {
    id: 'td-012',
    name: '粉紅少女',
    description: '甜美外表下藏著強大實力',
    idleGif: '/sprites/td-012-idle.gif',
    walkGif: '/sprites/td-012-walk.gif',
    restGif: '/sprites/td-012-rest.gif',
  },
  {
    id: 'td-013',
    name: '陽光女孩',
    description: '笑容感染全場，走到哪都帶來好心情',
    idleGif: '/sprites/td-013-idle.gif',
    walkGif: '/sprites/td-013-walk.gif',
    restGif: '/sprites/td-013-rest.gif',
  },
  {
    id: 'td-014',
    name: '深色系男孩',
    description: '神秘低調，但關鍵時刻超可靠',
    idleGif: '/sprites/td-014-idle.gif',
    walkGif: '/sprites/td-014-walk.gif',
    restGif: '/sprites/td-014-rest.gif',
  },
  {
    id: 'td-015',
    name: '長髮少女',
    description: '文靜溫柔，細心照顧身邊的人',
    idleGif: '/sprites/td-015-idle.gif',
    walkGif: '/sprites/td-015-walk.gif',
    restGif: '/sprites/td-015-rest.gif',
  },
  {
    id: 'td-016',
    name: '紅頭壯漢',
    description: '力氣大、心腸好，誰都搬得動',
    idleGif: '/sprites/td-016-idle.gif',
    walkGif: '/sprites/td-016-walk.gif',
    restGif: '/sprites/td-016-rest.gif',
  },
  {
    id: 'td-017',
    name: '紅衣男孩',
    description: '衝勁十足，做事風風火火',
    idleGif: '/sprites/td-017-idle.gif',
    walkGif: '/sprites/td-017-walk.gif',
    restGif: '/sprites/td-017-rest.gif',
  },
  {
    id: 'td-018',
    name: '輕便男孩',
    description: '輕裝上陣，跑腿最快',
    idleGif: '/sprites/td-018-idle.gif',
    walkGif: '/sprites/td-018-walk.gif',
    restGif: '/sprites/td-018-rest.gif',
  },
  {
    id: 'td-019',
    name: '復古女孩',
    description: '品味懷舊，老歌老電影信手拈來',
    idleGif: '/sprites/td-019-idle.gif',
    walkGif: '/sprites/td-019-walk.gif',
    restGif: '/sprites/td-019-rest.gif',
  },
  {
    id: 'td-020',
    name: '綠髮精靈',
    description: '來自魔法森林，帶來好運',
    idleGif: '/sprites/td-020-idle.gif',
    walkGif: '/sprites/td-020-walk.gif',
    restGif: '/sprites/td-020-rest.gif',
  },
  {
    id: 'td-021',
    name: '普通男孩',
    description: '沒有超能力，但努力是最強武器',
    idleGif: '/sprites/td-021-idle.gif',
    walkGif: '/sprites/td-021-walk.gif',
    restGif: '/sprites/td-021-rest.gif',
  },
  {
    id: 'td-022',
    name: '短髮女俠',
    description: '俐落果斷，不拖泥帶水',
    idleGif: '/sprites/td-022-idle.gif',
    walkGif: '/sprites/td-022-walk.gif',
    restGif: '/sprites/td-022-rest.gif',
  },
  {
    id: 'td-023',
    name: '銀髮戰士',
    description: '經歷千場戰鬥，無懼任何挑戰',
    idleGif: '/sprites/td-023-idle.gif',
    walkGif: '/sprites/td-023-walk.gif',
    restGif: '/sprites/td-023-rest.gif',
  },
  {
    id: 'td-024',
    name: '眼鏡女孩',
    description: '知識就是力量，圖書館的常客',
    idleGif: '/sprites/td-024-idle.gif',
    walkGif: '/sprites/td-024-walk.gif',
    restGif: '/sprites/td-024-rest.gif',
  },
  {
    id: 'td-025',
    name: '元氣女孩',
    description: '每天早上精神滿滿，讓人羨慕',
    idleGif: '/sprites/td-025-idle.gif',
    walkGif: '/sprites/td-025-walk.gif',
    restGif: '/sprites/td-025-rest.gif',
  },
  {
    id: 'td-026',
    name: '紅髮女孩',
    description: '熱情如火，做事全力以赴',
    idleGif: '/sprites/td-026-idle.gif',
    walkGif: '/sprites/td-026-walk.gif',
    restGif: '/sprites/td-026-rest.gif',
  },
  {
    id: 'td-027',
    name: '灰衣隱者',
    description: '行蹤神秘，背後故事說不完',
    idleGif: '/sprites/td-027-idle.gif',
    walkGif: '/sprites/td-027-walk.gif',
    restGif: '/sprites/td-027-rest.gif',
  },
  {
    id: 'td-028',
    name: '綠色怪物',
    description: '外型嚇人，其實溫柔得很',
    idleGif: '/sprites/td-028-idle.gif',
    walkGif: '/sprites/td-028-walk.gif',
    restGif: '/sprites/td-028-rest.gif',
  },
  {
    id: 'td-029',
    name: '小綠人',
    description: '來自遙遠星球，對地球充滿好奇',
    idleGif: '/sprites/td-029-idle.gif',
    walkGif: '/sprites/td-029-walk.gif',
    restGif: '/sprites/td-029-rest.gif',
  },
  {
    id: 'td-030',
    name: '橘髮少女',
    description: '話不多，但每句話都算數',
    idleGif: '/sprites/td-030-idle.gif',
    walkGif: '/sprites/td-030-walk.gif',
    restGif: '/sprites/td-030-rest.gif',
  },
  {
    id: 'td-031',
    name: '紅衣女俠',
    description: '行俠仗義，見不得不公平的事',
    idleGif: '/sprites/td-031-idle.gif',
    walkGif: '/sprites/td-031-walk.gif',
    restGif: '/sprites/td-031-rest.gif',
  },
  {
    id: 'td-032',
    name: '火焰頭女孩',
    description: '熱力四射，走進哪裡都是焦點',
    idleGif: '/sprites/td-032-idle.gif',
    walkGif: '/sprites/td-032-walk.gif',
    restGif: '/sprites/td-032-rest.gif',
  },
  {
    id: 'td-033',
    name: '翠髮女巫',
    description: '懂一點魔法，加班就靠符咒',
    idleGif: '/sprites/td-033-idle.gif',
    walkGif: '/sprites/td-033-walk.gif',
    restGif: '/sprites/td-033-rest.gif',
  },
  {
    id: 'td-034',
    name: '紅短髮姐',
    description: '直率不繞彎，省時省力',
    idleGif: '/sprites/td-034-idle.gif',
    walkGif: '/sprites/td-034-walk.gif',
    restGif: '/sprites/td-034-rest.gif',
  },
  {
    id: 'td-035',
    name: '石頭巨人',
    description: '沉穩如岩石，任何壓力都壓不垮',
    idleGif: '/sprites/td-035-idle.gif',
    walkGif: '/sprites/td-035-walk.gif',
    restGif: '/sprites/td-035-rest.gif',
  },
  {
    id: 'td-036',
    name: '外星訪客',
    description: '用外星視角看問題，總有新觀點',
    idleGif: '/sprites/td-036-idle.gif',
    walkGif: '/sprites/td-036-walk.gif',
    restGif: '/sprites/td-036-rest.gif',
  },
  {
    id: 'td-037',
    name: '地獄惡鬼',
    description: '看起來很嚇人，其實只是在裝',
    idleGif: '/sprites/td-037-idle.gif',
    walkGif: '/sprites/td-037-walk.gif',
    restGif: '/sprites/td-037-rest.gif',
  },
  {
    id: 'td-038',
    name: '赤紅惡魔',
    description: '工作魔人，不達目標不罷休',
    idleGif: '/sprites/td-038-idle.gif',
    walkGif: '/sprites/td-038-walk.gif',
    restGif: '/sprites/td-038-rest.gif',
  },
  {
    id: 'td-039',
    name: '格鬥家',
    description: '身手矯健，截止日前的最強武器',
    idleGif: '/sprites/td-039-idle.gif',
    walkGif: '/sprites/td-039-walk.gif',
    restGif: '/sprites/td-039-rest.gif',
  },
]

/** 根據 ID 取得 sprite，找不到時回傳第一個 */
export function getSpriteById(id?: string | null): SpriteDefinition {
  if (!id) return SPRITE_REGISTRY[0]
  return SPRITE_REGISTRY.find(s => s.id === id) ?? SPRITE_REGISTRY[0]
}
